[[gallery]]
title = "Nära 1"
filename = "nara-01.jpeg"
featured = true

[[gallery]]
title = "Nära 2"
filename = "nara-02.jpeg"

[[gallery]]
title = "Nära 3"
filename = "nara-03.jpeg"

[[gallery]]
title = "Nära 4"
filename = "nara-04.jpeg"

[[gallery]]
title = "Nära 5"
filename = "nara-05.jpeg"

[[gallery]]
title = "Nära 6"
filename = "nara-06.jpeg"

[[gallery]]
title = "Nära 7"
filename = "nara-07.jpeg"

[[gallery]]
title = "Nära 8"
filename = "nara-08.jpeg"

[[gallery]]
title = "Nära 9"
filename = "nara-09.jpeg"

[[gallery]]
title = "Nära 10"
filename = "nara-10.jpeg"

[[gallery]]
title = "Nära 11"
filename = "nara-11.jpeg"

[[gallery]]
title = "Nära 12"
filename = "nara-12.jpeg"
