title = "Elektrubadur"
description = "Personal web page of Björn Lindström"
base_url = "https://elektrubadur.se"
theme = "brutal-gutenberg"
highlight_code = false
generate_rss = true
generate_tags_pages = true

[extra.author]
name = "Björn Lindström"
