title = "Elektrubadur"
description = "Personal web page of Björn Lindström"
base_url = "__PREFIX__"
theme = "elektrubadur"
highlight_code = false
generate_rss = true
generate_tags_pages = true
taxonomies = [
    { name = "categories", rss = true, paginate_by = 10 },
]

[extra.author]
name = "Björn Lindström"
