title = "Elektrubadur"
description = "Personal web page of Björn Lindström"
base_url = "__PREFIX__"
highlight_code = false
generate_rss = true
generate_tags_pages = true
compile_sass = true
taxonomies = [
    { name = "categories", rss = true, paginate_by = 10 },
]
default_language = "en"

[extra.author]
name = "Björn Lindström"
