title = "Elektrubadur"
description = "Personal web page of Björn Lindström"
base_url = "https://elektrubadur.se"
highlight_code = true
highlight_theme = "classic-modified"
generate_feed = true
feed_filename = "rss.xml"
generate_tags_pages = true
compile_sass = true
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = false, paginate_by = 10 },
]
default_language = "en"

[extra.author]
name = "Björn Lindström"
