title = "Elektrubadur"
baseURL = "https://elektrubadur.se"
canonifyURLs = true
copyright = "© 2010–2026 Björn Lindström"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableGitInfo = false
enableRobotsTXT = true
timeZone = "Europe/Stockholm"
disableAliases = true

[outputs]
home = ["html", "atom", "redirects"]
page = ["html"]
section = ["html"]
taxonomy = ["html"]
term = ["html", "atom"]

[outputFormats.atom]
basename = "feed"
mediaType = "application/atom+xml"
noUgly = true

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[mediaTypes."text/vnd.statichost.redirects"]

[outputFormats.redirects]
mediatype = "text/vnd.statichost.redirects"
baseName = "_redirects"
isPlainText = true

[markup.highlight]
style = "modus-operandi"
noClasses = false

[markup.goldmark.parser]
autoDefinitionTermID = false
autoHeadingID = false

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Personal web page of Björn Lindström"

[params.author]
name = "Björn Lindström"
email = "bkhl@elektrubadur.se"
