name = "elektrubadur-gutenberg"
description = "Theme for elektrubadur.se"
license = ""
homepage = ""
min_version = "0.5.0"
demo = "https://elektrubadur.se"

[extra]

[author]
name = "Björn Lindström"
homepage = "https://elektrubadur.se"
