[[gallery]]
title = "Attention"
filename = "attention.jpeg"
featured = true

[[gallery]]
title = "Pause"
filename = "pause.jpeg"

[[gallery]]
title = "Aim"
filename = "aim.jpeg"

[[gallery]]
title = "Needlework"
filename = "needlework.jpeg"
