[[gallery]]
title = "Buffalo"
description = "Buffalo."
filename = "buffalo.jpeg"
featured = true

[[gallery]]
title = "Deer"
description = "Deer."
filename = "deer.jpeg"

[[gallery]]
title = "Houses"
description = "Accomodations."
filename = "houses.jpeg"

[[gallery]]
title = "Peacock"
description = "Peacock."
filename = "peacock.jpeg"

[[gallery]]
title = "River"
description = "River flowing past nearby Sam Chuk market."
filename = "river.jpeg"
