[[gallery]]
title = "Mechatronic 1"
filename = "mechatronic-1.jpeg"
featured = true

[[gallery]]
title = "Mechatronic 2"
filename = "mechatronic-2.jpeg"

[[gallery]]
title = "Mechatronic 3"
filename = "mechatronic-3.jpeg"

[[gallery]]
title = "Mechatronic 4"
filename = "mechatronic-4.jpeg"
