[[gallery]]
title = "Workman"
filename = "workman.jpeg"
featured = true

[[gallery]]
title = "Sentry"
filename = "sentry.jpeg"

[[gallery]]
title = "Come Prepared"
filename = "come_prepared.jpeg"

[[gallery]]
title = "Strange planets"
filename = "strange_planets.jpeg"
