[[gallery]]
description = "Artificial Sun"
filename = "artificial-sun.jpeg"
featured = true

[[gallery]]
description = "Bell Tower"
filename = "bell-tower.jpeg"

[[gallery]]
description = "Off the Fence"
filename = "off-the-fence.jpeg"

[[gallery]]
description = "Riverside"
filename = "riverside.jpeg"

[[gallery]]
description = "The Party Line"
filename = "the-party-line.jpeg"
