---
name: Build

on:
  push:
    branches:
      - trigger-statichost

jobs:
  build:
    name: Build web site
    runs-on: ubuntu-latest
    steps:
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Install HTML Tidy and XMLStarlet
        run: sudo apt-get -y install tidy xmlstarlet

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check out dotfiles repository
        uses: actions/checkout@v4
        with:
          repository: bkhl/dotfiles
          path: dotfiles
          fetch-depth: 0

      - name: Copy Emacs configuration into contents directory
        run: >-
          install -v -m 0644 -T
          dotfiles/.emacs.d/configuration.org
          content/articles/emacs-configuration.org

      - name: Build web site
        run: bash build.sh
        env:
          DESTINATION: public

      - name: Validate web site
        uses: docker://ghcr.io/validator/validator:latest
        with:
          args: vnu --skip-non-html --also-check-css --also-check-svg public

      - name: Upload web site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
          retention-days: 7

  publish:
    name: Publish web site
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository (current branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "${{ github.workspace }}/${{ github.event.repository.name }}"

      - name: Check out repository (public branch)
        uses: actions/checkout@v4
        with:
          path: "${{ github.workspace }}/${{ github.event.repository.name }}-public"
          ref: public
          fetch-depth: 0

      - name: Download web site artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: "${{ github.workspace }}/public"

      - name: Publish web site
        run: bash "${{ github.workspace }}/${{ github.event.repository.name }}/publish.sh"
        env:
          SOURCE: "${{ github.workspace }}/${{ github.event.repository.name }}"
          PREV_PUBLIC: "${{ github.workspace }}/${{ github.event.repository.name }}-public"
          PUBLIC: "${{ github.workspace }}/public"
          PUSH_URL: >-
            https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          SITE_NAME: elektrubadur-se
