---
name: Check links

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check links
        uses: docker://docker.io/tennox/linkcheck:latest
        with:
          args: >-
            --show-redirects
            --check-anchors
            --external
            --skip-file linkcheck_skipfile.txt
            "https://elektrubadur.se"
