---
name: Check links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository public branch
        uses: actions/checkout@v6
        with:
          ref: public
          fetch-depth: 0

      - name: Check links
        uses: docker://docker.io/lycheeverse/lychee:latest
        with:
          args: >-
            -v
            --host-concurrency=1
            --host-request-interval=1s
            --max-redirects=2
            --root-dir="/github/workspace"
            --remap="^https://elektrubadur\.se file:///github/workspace"
            --exclude="^https://www.linkedin.com(/|$)"
            --exclude="^https://web\.archive\.org(/|$)"
            .
