---
name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Install HTML Tidy and XMLStarlet
        run: sudo apt-get -y install tidy xmlstarlet

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build web site
        run: bash build/build.sh

      - name: Validate web site
        uses: docker://ghcr.io/validator/validator:latest
        with:
          args: vnu --skip-non-html --also-check-css --also-check-svg public

      - name: Upload web site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
          retention-days: 7

  publish:
    name: Publish
    needs: build
    if: >-
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository (current branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source

      - name: Check out repository (public branch)
        uses: actions/checkout@v4
        with:
          ref: public
          path: prev-public
          token: "${{ github.token }}"
          fetch-depth: 0

      - name: Download web site artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: "${{ github.workspace }}/public"

      - name: Publish web site
        run: bash source/build/publish.sh
        env:
          SOURCE: "${{ github.workspace }}/source"
          PREV_PUBLIC: "${{ github.workspace }}/prev-public"
          PUBLIC: "${{ github.workspace }}/public"
          SITE_NAME: elektrubadur-se
